# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WizardPageVariables.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WizardPageVariables(object):
	def setupUi(self, WizardPageVariables):
		WizardPageVariables.setObjectName("WizardPageVariables")
		WizardPageVariables.resize(1102, 539)
		self.verticalLayout = QtWidgets.QVBoxLayout(WizardPageVariables)
		self.verticalLayout.setObjectName("verticalLayout")
		self.groupBox = QtWidgets.QGroupBox(WizardPageVariables)
		self.groupBox.setObjectName("groupBox")
		self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
		self.gridLayout.setObjectName("gridLayout")
		self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
		self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
		self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.tableWidget.setRowCount(0)
		self.tableWidget.setColumnCount(9)
		self.tableWidget.setObjectName("tableWidget")
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(8, item)
		self.tableWidget.horizontalHeader().setStretchLastSection(True)
		self.tableWidget.verticalHeader().setVisible(False)
		self.gridLayout.addWidget(self.tableWidget, 0, 0, 3, 1)
		self.toolButtonAdd = QtWidgets.QToolButton(self.groupBox)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/gfx/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButtonAdd.setIcon(icon)
		self.toolButtonAdd.setIconSize(QtCore.QSize(24, 24))
		self.toolButtonAdd.setObjectName("toolButtonAdd")
		self.gridLayout.addWidget(self.toolButtonAdd, 0, 1, 1, 1)
		self.toolButtonRemove = QtWidgets.QToolButton(self.groupBox)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/gfx/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButtonRemove.setIcon(icon1)
		self.toolButtonRemove.setIconSize(QtCore.QSize(24, 24))
		self.toolButtonRemove.setObjectName("toolButtonRemove")
		self.gridLayout.addWidget(self.toolButtonRemove, 1, 1, 1, 1)
		spacerItem = QtWidgets.QSpacerItem(20, 236, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
		self.verticalLayout.addWidget(self.groupBox)
		self.groupBox_2 = QtWidgets.QGroupBox(WizardPageVariables)
		self.groupBox_2.setObjectName("groupBox_2")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.labelUnit = QtWidgets.QLabel(self.groupBox_2)
		self.labelUnit.setObjectName("labelUnit")
		self.gridLayout_3.addWidget(self.labelUnit, 2, 0, 1, 1)
		self.label_6 = QtWidgets.QLabel(self.groupBox_2)
		self.label_6.setObjectName("label_6")
		self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
		self.gridLayout_2 = QtWidgets.QGridLayout()
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.comboBoxCausality = QtWidgets.QComboBox(self.groupBox_2)
		self.comboBoxCausality.setObjectName("comboBoxCausality")
		self.comboBoxCausality.addItem("")
		self.comboBoxCausality.addItem("")
		self.comboBoxCausality.addItem("")
		self.comboBoxCausality.addItem("")
		self.comboBoxCausality.addItem("")
		self.comboBoxCausality.addItem("")
		self.gridLayout_2.addWidget(self.comboBoxCausality, 2, 3, 1, 1)
		self.spinBoxValueRef = QtWidgets.QSpinBox(self.groupBox_2)
		self.spinBoxValueRef.setMinimum(-1)
		self.spinBoxValueRef.setMaximum(9999)
		self.spinBoxValueRef.setProperty("value", -1)
		self.spinBoxValueRef.setObjectName("spinBoxValueRef")
		self.gridLayout_2.addWidget(self.spinBoxValueRef, 2, 1, 1, 1)
		self.label = QtWidgets.QLabel(self.groupBox_2)
		self.label.setObjectName("label")
		self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
		self.label_2 = QtWidgets.QLabel(self.groupBox_2)
		self.label_2.setObjectName("label_2")
		self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
		self.comboBoxInitial = QtWidgets.QComboBox(self.groupBox_2)
		self.comboBoxInitial.setObjectName("comboBoxInitial")
		self.comboBoxInitial.addItem("")
		self.comboBoxInitial.addItem("")
		self.comboBoxInitial.addItem("")
		self.gridLayout_2.addWidget(self.comboBoxInitial, 3, 3, 1, 1)
		self.label_4 = QtWidgets.QLabel(self.groupBox_2)
		self.label_4.setObjectName("label_4")
		self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
		self.comboBoxVariability = QtWidgets.QComboBox(self.groupBox_2)
		self.comboBoxVariability.setObjectName("comboBoxVariability")
		self.comboBoxVariability.addItem("")
		self.comboBoxVariability.addItem("")
		self.comboBoxVariability.addItem("")
		self.comboBoxVariability.addItem("")
		self.comboBoxVariability.addItem("")
		self.gridLayout_2.addWidget(self.comboBoxVariability, 0, 3, 1, 1)
		self.label_5 = QtWidgets.QLabel(self.groupBox_2)
		self.label_5.setObjectName("label_5")
		self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
		self.label_3 = QtWidgets.QLabel(self.groupBox_2)
		self.label_3.setObjectName("label_3")
		self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
		self.lineEditName = QtWidgets.QLineEdit(self.groupBox_2)
		self.lineEditName.setObjectName("lineEditName")
		self.gridLayout_2.addWidget(self.lineEditName, 0, 1, 1, 1)
		self.label_9 = QtWidgets.QLabel(self.groupBox_2)
		self.label_9.setObjectName("label_9")
		self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
		self.lineEditDescription = QtWidgets.QLineEdit(self.groupBox_2)
		self.lineEditDescription.setObjectName("lineEditDescription")
		self.gridLayout_2.addWidget(self.lineEditDescription, 1, 1, 1, 3)
		self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 3)
		self.comboBoxTypeID = QtWidgets.QComboBox(self.groupBox_2)
		self.comboBoxTypeID.setObjectName("comboBoxTypeID")
		self.comboBoxTypeID.addItem("")
		self.comboBoxTypeID.addItem("")
		self.comboBoxTypeID.addItem("")
		self.comboBoxTypeID.addItem("")
		self.gridLayout_3.addWidget(self.comboBoxTypeID, 1, 2, 1, 1)
		self.lineEditStart = QtWidgets.QLineEdit(self.groupBox_2)
		self.lineEditStart.setObjectName("lineEditStart")
		self.gridLayout_3.addWidget(self.lineEditStart, 3, 2, 1, 1)
		self.label_7 = QtWidgets.QLabel(self.groupBox_2)
		self.label_7.setObjectName("label_7")
		self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
		self.lineEditUnit = QtWidgets.QLineEdit(self.groupBox_2)
		self.lineEditUnit.setObjectName("lineEditUnit")
		self.gridLayout_3.addWidget(self.lineEditUnit, 2, 2, 1, 1)
		self.verticalLayout.addWidget(self.groupBox_2)
		self.groupBox_3 = QtWidgets.QGroupBox(WizardPageVariables)
		self.groupBox_3.setObjectName("groupBox_3")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.label_8 = QtWidgets.QLabel(self.groupBox_3)
		self.label_8.setObjectName("label_8")
		self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
		self.spinBoxContinuousStates = QtWidgets.QSpinBox(self.groupBox_3)
		self.spinBoxContinuousStates.setObjectName("spinBoxContinuousStates")
		self.gridLayout_4.addWidget(self.spinBoxContinuousStates, 0, 1, 1, 1)
		self.verticalLayout.addWidget(self.groupBox_3)

		self.retranslateUi(WizardPageVariables)
		self.comboBoxCausality.setCurrentIndex(4)
		self.comboBoxVariability.setCurrentIndex(4)
		QtCore.QMetaObject.connectSlotsByName(WizardPageVariables)

	def retranslateUi(self, WizardPageVariables):
		_translate = QtCore.QCoreApplication.translate
		WizardPageVariables.setWindowTitle(_translate("WizardPageVariables", "Form"))
		self.groupBox.setTitle(_translate("WizardPageVariables", "Defined parameters and variables"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("WizardPageVariables", "Name"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("WizardPageVariables", "ValueRef"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("WizardPageVariables", "Variability"))
		item = self.tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("WizardPageVariables", "Causality"))
		item = self.tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("WizardPageVariables", "Initial"))
		item = self.tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("WizardPageVariables", "Type"))
		item = self.tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("WizardPageVariables", "Start value"))
		item = self.tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("WizardPageVariables", "Unit"))
		item = self.tableWidget.horizontalHeaderItem(8)
		item.setText(_translate("WizardPageVariables", "Description"))
		self.groupBox_2.setTitle(_translate("WizardPageVariables", "Properties"))
		self.labelUnit.setText(_translate("WizardPageVariables", "Unit:"))
		self.label_6.setText(_translate("WizardPageVariables", "Start value:"))
		self.comboBoxCausality.setItemText(0, _translate("WizardPageVariables", "parameter"))
		self.comboBoxCausality.setItemText(1, _translate("WizardPageVariables", "calculatedParameter"))
		self.comboBoxCausality.setItemText(2, _translate("WizardPageVariables", "input"))
		self.comboBoxCausality.setItemText(3, _translate("WizardPageVariables", "output"))
		self.comboBoxCausality.setItemText(4, _translate("WizardPageVariables", "local"))
		self.comboBoxCausality.setItemText(5, _translate("WizardPageVariables", "independent"))
		self.label.setText(_translate("WizardPageVariables", "Name:"))
		self.label_2.setText(_translate("WizardPageVariables", "Value reference (-1 for auto):"))
		self.comboBoxInitial.setItemText(0, _translate("WizardPageVariables", "exact"))
		self.comboBoxInitial.setItemText(1, _translate("WizardPageVariables", "approx"))
		self.comboBoxInitial.setItemText(2, _translate("WizardPageVariables", "calculated"))
		self.label_4.setText(_translate("WizardPageVariables", "Causality:"))
		self.comboBoxVariability.setItemText(0, _translate("WizardPageVariables", "constant"))
		self.comboBoxVariability.setItemText(1, _translate("WizardPageVariables", "fixed"))
		self.comboBoxVariability.setItemText(2, _translate("WizardPageVariables", "tunable"))
		self.comboBoxVariability.setItemText(3, _translate("WizardPageVariables", "discrete"))
		self.comboBoxVariability.setItemText(4, _translate("WizardPageVariables", "continuous"))
		self.label_5.setText(_translate("WizardPageVariables", "Initial:"))
		self.label_3.setText(_translate("WizardPageVariables", "Variability:"))
		self.label_9.setText(_translate("WizardPageVariables", "Description:"))
		self.comboBoxTypeID.setItemText(0, _translate("WizardPageVariables", "Real"))
		self.comboBoxTypeID.setItemText(1, _translate("WizardPageVariables", "Integer"))
		self.comboBoxTypeID.setItemText(2, _translate("WizardPageVariables", "Boolean"))
		self.comboBoxTypeID.setItemText(3, _translate("WizardPageVariables", "String"))
		self.label_7.setText(_translate("WizardPageVariables", "Type:"))
		self.groupBox_3.setTitle(_translate("WizardPageVariables", "Continuous states"))
		self.label_8.setText(_translate("WizardPageVariables", "Number of continuous states in the model:"))

import FMIGenerator_rc
